// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockModelInterface creates a new instance of MockModelInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelInterface {
	mock := &MockModelInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModelInterface is an autogenerated mock type for the ModelInterface type
type MockModelInterface struct {
	mock.Mock
}

type MockModelInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelInterface) EXPECT() *MockModelInterface_Expecter {
	return &MockModelInterface_Expecter{mock: &_m.Mock}
}

// TableName provides a mock function for the type MockModelInterface
func (_mock *MockModelInterface) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockModelInterface_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type MockModelInterface_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *MockModelInterface_Expecter) TableName() *MockModelInterface_TableName_Call {
	return &MockModelInterface_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *MockModelInterface_TableName_Call) Run(run func()) *MockModelInterface_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModelInterface_TableName_Call) Return(s string) *MockModelInterface_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockModelInterface_TableName_Call) RunAndReturn(run func() string) *MockModelInterface_TableName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionManagerInterface creates a new instance of MockTransactionManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManagerInterface {
	mock := &MockTransactionManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionManagerInterface is an autogenerated mock type for the TransactionManagerInterface type
type MockTransactionManagerInterface struct {
	mock.Mock
}

type MockTransactionManagerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManagerInterface) EXPECT() *MockTransactionManagerInterface_Expecter {
	return &MockTransactionManagerInterface_Expecter{mock: &_m.Mock}
}

// BeginTransaction provides a mock function for the type MockTransactionManagerInterface
func (_mock *MockTransactionManagerInterface) BeginTransaction(ctx context.Context) (context.Context, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionManagerInterface_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type MockTransactionManagerInterface_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionManagerInterface_Expecter) BeginTransaction(ctx interface{}) *MockTransactionManagerInterface_BeginTransaction_Call {
	return &MockTransactionManagerInterface_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction", ctx)}
}

func (_c *MockTransactionManagerInterface_BeginTransaction_Call) Run(run func(ctx context.Context)) *MockTransactionManagerInterface_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionManagerInterface_BeginTransaction_Call) Return(context1 context.Context, err error) *MockTransactionManagerInterface_BeginTransaction_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *MockTransactionManagerInterface_BeginTransaction_Call) RunAndReturn(run func(ctx context.Context) (context.Context, error)) *MockTransactionManagerInterface_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTransaction provides a mock function for the type MockTransactionManagerInterface
func (_mock *MockTransactionManagerInterface) CommitTransaction(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManagerInterface_CommitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTransaction'
type MockTransactionManagerInterface_CommitTransaction_Call struct {
	*mock.Call
}

// CommitTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionManagerInterface_Expecter) CommitTransaction(ctx interface{}) *MockTransactionManagerInterface_CommitTransaction_Call {
	return &MockTransactionManagerInterface_CommitTransaction_Call{Call: _e.mock.On("CommitTransaction", ctx)}
}

func (_c *MockTransactionManagerInterface_CommitTransaction_Call) Run(run func(ctx context.Context)) *MockTransactionManagerInterface_CommitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionManagerInterface_CommitTransaction_Call) Return(err error) *MockTransactionManagerInterface_CommitTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManagerInterface_CommitTransaction_Call) RunAndReturn(run func(ctx context.Context) error) *MockTransactionManagerInterface_CommitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// IsTransactionOwner provides a mock function for the type MockTransactionManagerInterface
func (_mock *MockTransactionManagerInterface) IsTransactionOwner(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsTransactionOwner")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTransactionManagerInterface_IsTransactionOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTransactionOwner'
type MockTransactionManagerInterface_IsTransactionOwner_Call struct {
	*mock.Call
}

// IsTransactionOwner is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionManagerInterface_Expecter) IsTransactionOwner(ctx interface{}) *MockTransactionManagerInterface_IsTransactionOwner_Call {
	return &MockTransactionManagerInterface_IsTransactionOwner_Call{Call: _e.mock.On("IsTransactionOwner", ctx)}
}

func (_c *MockTransactionManagerInterface_IsTransactionOwner_Call) Run(run func(ctx context.Context)) *MockTransactionManagerInterface_IsTransactionOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionManagerInterface_IsTransactionOwner_Call) Return(b bool) *MockTransactionManagerInterface_IsTransactionOwner_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTransactionManagerInterface_IsTransactionOwner_Call) RunAndReturn(run func(ctx context.Context) bool) *MockTransactionManagerInterface_IsTransactionOwner_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackTransaction provides a mock function for the type MockTransactionManagerInterface
func (_mock *MockTransactionManagerInterface) RollbackTransaction(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManagerInterface_RollbackTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackTransaction'
type MockTransactionManagerInterface_RollbackTransaction_Call struct {
	*mock.Call
}

// RollbackTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionManagerInterface_Expecter) RollbackTransaction(ctx interface{}) *MockTransactionManagerInterface_RollbackTransaction_Call {
	return &MockTransactionManagerInterface_RollbackTransaction_Call{Call: _e.mock.On("RollbackTransaction", ctx)}
}

func (_c *MockTransactionManagerInterface_RollbackTransaction_Call) Run(run func(ctx context.Context)) *MockTransactionManagerInterface_RollbackTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionManagerInterface_RollbackTransaction_Call) Return(err error) *MockTransactionManagerInterface_RollbackTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManagerInterface_RollbackTransaction_Call) RunAndReturn(run func(ctx context.Context) error) *MockTransactionManagerInterface_RollbackTransaction_Call {
	_c.Call.Return(run)
	return _c
}
