// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/scienceandcode/nucleus-api/internal/app/interfaces"
	"github.com/scienceandcode/nucleus-api/internal/app/messages"
	"github.com/scienceandcode/nucleus-api/internal/domain/user/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailConfirmationServiceInterface creates a new instance of MockEmailConfirmationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailConfirmationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailConfirmationServiceInterface {
	mock := &MockEmailConfirmationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailConfirmationServiceInterface is an autogenerated mock type for the EmailConfirmationServiceInterface type
type MockEmailConfirmationServiceInterface struct {
	mock.Mock
}

type MockEmailConfirmationServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailConfirmationServiceInterface) EXPECT() *MockEmailConfirmationServiceInterface_Expecter {
	return &MockEmailConfirmationServiceInterface_Expecter{mock: &_m.Mock}
}

// GenerateConfirmationToken provides a mock function for the type MockEmailConfirmationServiceInterface
func (_mock *MockEmailConfirmationServiceInterface) GenerateConfirmationToken(ctx context.Context, userID uint64, email string) (string, error) {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateConfirmationToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (string, error)); ok {
		return returnFunc(ctx, userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) string); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateConfirmationToken'
type MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call struct {
	*mock.Call
}

// GenerateConfirmationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - email string
func (_e *MockEmailConfirmationServiceInterface_Expecter) GenerateConfirmationToken(ctx interface{}, userID interface{}, email interface{}) *MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call {
	return &MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call{Call: _e.mock.On("GenerateConfirmationToken", ctx, userID, email)}
}

func (_c *MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call) Run(run func(ctx context.Context, userID uint64, email string)) *MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call) Return(s string, err error) *MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call) RunAndReturn(run func(ctx context.Context, userID uint64, email string) (string, error)) *MockEmailConfirmationServiceInterface_GenerateConfirmationToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfirmationToken provides a mock function for the type MockEmailConfirmationServiceInterface
func (_mock *MockEmailConfirmationServiceInterface) ValidateConfirmationToken(ctx context.Context, tokenString string) (*interfaces.EmailConfirmationClaims, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfirmationToken")
	}

	var r0 *interfaces.EmailConfirmationClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*interfaces.EmailConfirmationClaims, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *interfaces.EmailConfirmationClaims); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.EmailConfirmationClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfirmationToken'
type MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call struct {
	*mock.Call
}

// ValidateConfirmationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockEmailConfirmationServiceInterface_Expecter) ValidateConfirmationToken(ctx interface{}, tokenString interface{}) *MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call {
	return &MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call{Call: _e.mock.On("ValidateConfirmationToken", ctx, tokenString)}
}

func (_c *MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call) Return(emailConfirmationClaims *interfaces.EmailConfirmationClaims, err error) *MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call {
	_c.Call.Return(emailConfirmationClaims, err)
	return _c
}

func (_c *MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*interfaces.EmailConfirmationClaims, error)) *MockEmailConfirmationServiceInterface_ValidateConfirmationToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailServiceInterface creates a new instance of MockEmailServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailServiceInterface {
	mock := &MockEmailServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailServiceInterface is an autogenerated mock type for the EmailServiceInterface type
type MockEmailServiceInterface struct {
	mock.Mock
}

type MockEmailServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailServiceInterface) EXPECT() *MockEmailServiceInterface_Expecter {
	return &MockEmailServiceInterface_Expecter{mock: &_m.Mock}
}

// SendEmailConfirmation provides a mock function for the type MockEmailServiceInterface
func (_mock *MockEmailServiceInterface) SendEmailConfirmation(ctx context.Context, email string, confirmationToken string) error {
	ret := _mock.Called(ctx, email, confirmationToken)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailConfirmation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, confirmationToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailServiceInterface_SendEmailConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailConfirmation'
type MockEmailServiceInterface_SendEmailConfirmation_Call struct {
	*mock.Call
}

// SendEmailConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - confirmationToken string
func (_e *MockEmailServiceInterface_Expecter) SendEmailConfirmation(ctx interface{}, email interface{}, confirmationToken interface{}) *MockEmailServiceInterface_SendEmailConfirmation_Call {
	return &MockEmailServiceInterface_SendEmailConfirmation_Call{Call: _e.mock.On("SendEmailConfirmation", ctx, email, confirmationToken)}
}

func (_c *MockEmailServiceInterface_SendEmailConfirmation_Call) Run(run func(ctx context.Context, email string, confirmationToken string)) *MockEmailServiceInterface_SendEmailConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailServiceInterface_SendEmailConfirmation_Call) Return(err error) *MockEmailServiceInterface_SendEmailConfirmation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailServiceInterface_SendEmailConfirmation_Call) RunAndReturn(run func(ctx context.Context, email string, confirmationToken string) error) *MockEmailServiceInterface_SendEmailConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// SendPasswordRecoveryEmail provides a mock function for the type MockEmailServiceInterface
func (_mock *MockEmailServiceInterface) SendPasswordRecoveryEmail(ctx context.Context, email string, temporaryPassword string) error {
	ret := _mock.Called(ctx, email, temporaryPassword)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordRecoveryEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, temporaryPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailServiceInterface_SendPasswordRecoveryEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordRecoveryEmail'
type MockEmailServiceInterface_SendPasswordRecoveryEmail_Call struct {
	*mock.Call
}

// SendPasswordRecoveryEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - temporaryPassword string
func (_e *MockEmailServiceInterface_Expecter) SendPasswordRecoveryEmail(ctx interface{}, email interface{}, temporaryPassword interface{}) *MockEmailServiceInterface_SendPasswordRecoveryEmail_Call {
	return &MockEmailServiceInterface_SendPasswordRecoveryEmail_Call{Call: _e.mock.On("SendPasswordRecoveryEmail", ctx, email, temporaryPassword)}
}

func (_c *MockEmailServiceInterface_SendPasswordRecoveryEmail_Call) Run(run func(ctx context.Context, email string, temporaryPassword string)) *MockEmailServiceInterface_SendPasswordRecoveryEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailServiceInterface_SendPasswordRecoveryEmail_Call) Return(err error) *MockEmailServiceInterface_SendPasswordRecoveryEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailServiceInterface_SendPasswordRecoveryEmail_Call) RunAndReturn(run func(ctx context.Context, email string, temporaryPassword string) error) *MockEmailServiceInterface_SendPasswordRecoveryEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtServiceInterface creates a new instance of MockJwtServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtServiceInterface {
	mock := &MockJwtServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwtServiceInterface is an autogenerated mock type for the JwtServiceInterface type
type MockJwtServiceInterface struct {
	mock.Mock
}

type MockJwtServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtServiceInterface) EXPECT() *MockJwtServiceInterface_Expecter {
	return &MockJwtServiceInterface_Expecter{mock: &_m.Mock}
}

// GenerateIdentityToken provides a mock function for the type MockJwtServiceInterface
func (_mock *MockJwtServiceInterface) GenerateIdentityToken(ctx context.Context, user *entities.User) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateIdentityToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtServiceInterface_GenerateIdentityToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateIdentityToken'
type MockJwtServiceInterface_GenerateIdentityToken_Call struct {
	*mock.Call
}

// GenerateIdentityToken is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockJwtServiceInterface_Expecter) GenerateIdentityToken(ctx interface{}, user interface{}) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	return &MockJwtServiceInterface_GenerateIdentityToken_Call{Call: _e.mock.On("GenerateIdentityToken", ctx, user)}
}

func (_c *MockJwtServiceInterface_GenerateIdentityToken_Call) Run(run func(ctx context.Context, user *entities.User)) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwtServiceInterface_GenerateIdentityToken_Call) Return(s string, err error) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwtServiceInterface_GenerateIdentityToken_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) (string, error)) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskServiceInterface creates a new instance of MockTaskServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskServiceInterface {
	mock := &MockTaskServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskServiceInterface is an autogenerated mock type for the TaskServiceInterface type
type MockTaskServiceInterface struct {
	mock.Mock
}

type MockTaskServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskServiceInterface) EXPECT() *MockTaskServiceInterface_Expecter {
	return &MockTaskServiceInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Create(ctx context.Context, request *messages.CreateTaskRequestDTO) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.CreateTaskRequestDTO) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.CreateTaskRequestDTO) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.CreateTaskRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.CreateTaskRequestDTO
func (_e *MockTaskServiceInterface_Expecter) Create(ctx interface{}, request interface{}) *MockTaskServiceInterface_Create_Call {
	return &MockTaskServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockTaskServiceInterface_Create_Call) Run(run func(ctx context.Context, request *messages.CreateTaskRequestDTO)) *MockTaskServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.CreateTaskRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.CreateTaskRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Create_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_Create_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_Create_Call) RunAndReturn(run func(ctx context.Context, request *messages.CreateTaskRequestDTO) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Delete(ctx context.Context, id uint64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockTaskServiceInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskServiceInterface_Delete_Call {
	return &MockTaskServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskServiceInterface_Delete_Call) Run(run func(ctx context.Context, id uint64)) *MockTaskServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Delete_Call) Return(err error) *MockTaskServiceInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskServiceInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint64) error) *MockTaskServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Get(ctx context.Context, id uint64) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskServiceInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockTaskServiceInterface_Expecter) Get(ctx interface{}, id interface{}) *MockTaskServiceInterface_Get_Call {
	return &MockTaskServiceInterface_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTaskServiceInterface_Get_Call) Run(run func(ctx context.Context, id uint64)) *MockTaskServiceInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Get_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_Get_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_Get_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) List(ctx context.Context) ([]*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskServiceInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskServiceInterface_Expecter) List(ctx interface{}) *MockTaskServiceInterface_List_Call {
	return &MockTaskServiceInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTaskServiceInterface_List_Call) Run(run func(ctx context.Context)) *MockTaskServiceInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_List_Call) Return(taskResponseDTOs []*messages.TaskResponseDTO, err error) *MockTaskServiceInterface_List_Call {
	_c.Call.Return(taskResponseDTOs, err)
	return _c
}

func (_c *MockTaskServiceInterface_List_Call) RunAndReturn(run func(ctx context.Context) ([]*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Update(ctx context.Context, id uint64, request *messages.UpdateTaskRequestDTO) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskRequestDTO) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskRequestDTO) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *messages.UpdateTaskRequestDTO) error); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - request *messages.UpdateTaskRequestDTO
func (_e *MockTaskServiceInterface_Expecter) Update(ctx interface{}, id interface{}, request interface{}) *MockTaskServiceInterface_Update_Call {
	return &MockTaskServiceInterface_Update_Call{Call: _e.mock.On("Update", ctx, id, request)}
}

func (_c *MockTaskServiceInterface_Update_Call) Run(run func(ctx context.Context, id uint64, request *messages.UpdateTaskRequestDTO)) *MockTaskServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *messages.UpdateTaskRequestDTO
		if args[2] != nil {
			arg2 = args[2].(*messages.UpdateTaskRequestDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Update_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_Update_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_Update_Call) RunAndReturn(run func(ctx context.Context, id uint64, request *messages.UpdateTaskRequestDTO) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) UpdateStatus(ctx context.Context, id uint64, request *messages.UpdateTaskStatusRequestDTO) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskStatusRequestDTO) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskStatusRequestDTO) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *messages.UpdateTaskStatusRequestDTO) error); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTaskServiceInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - request *messages.UpdateTaskStatusRequestDTO
func (_e *MockTaskServiceInterface_Expecter) UpdateStatus(ctx interface{}, id interface{}, request interface{}) *MockTaskServiceInterface_UpdateStatus_Call {
	return &MockTaskServiceInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, request)}
}

func (_c *MockTaskServiceInterface_UpdateStatus_Call) Run(run func(ctx context.Context, id uint64, request *messages.UpdateTaskStatusRequestDTO)) *MockTaskServiceInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *messages.UpdateTaskStatusRequestDTO
		if args[2] != nil {
			arg2 = args[2].(*messages.UpdateTaskStatusRequestDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_UpdateStatus_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_UpdateStatus_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uint64, request *messages.UpdateTaskStatusRequestDTO) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAuthServiceInterface creates a new instance of MockUserAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAuthServiceInterface {
	mock := &MockUserAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAuthServiceInterface is an autogenerated mock type for the UserAuthServiceInterface type
type MockUserAuthServiceInterface struct {
	mock.Mock
}

type MockUserAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAuthServiceInterface) EXPECT() *MockUserAuthServiceInterface_Expecter {
	return &MockUserAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// ConfirmEmail provides a mock function for the type MockUserAuthServiceInterface
func (_mock *MockUserAuthServiceInterface) ConfirmEmail(ctx context.Context, token string) (*messages.ConfirmEmailResponseDTO, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmEmail")
	}

	var r0 *messages.ConfirmEmailResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*messages.ConfirmEmailResponseDTO, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *messages.ConfirmEmailResponseDTO); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.ConfirmEmailResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAuthServiceInterface_ConfirmEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmEmail'
type MockUserAuthServiceInterface_ConfirmEmail_Call struct {
	*mock.Call
}

// ConfirmEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserAuthServiceInterface_Expecter) ConfirmEmail(ctx interface{}, token interface{}) *MockUserAuthServiceInterface_ConfirmEmail_Call {
	return &MockUserAuthServiceInterface_ConfirmEmail_Call{Call: _e.mock.On("ConfirmEmail", ctx, token)}
}

func (_c *MockUserAuthServiceInterface_ConfirmEmail_Call) Run(run func(ctx context.Context, token string)) *MockUserAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAuthServiceInterface_ConfirmEmail_Call) Return(confirmEmailResponseDTO *messages.ConfirmEmailResponseDTO, err error) *MockUserAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Return(confirmEmailResponseDTO, err)
	return _c
}

func (_c *MockUserAuthServiceInterface_ConfirmEmail_Call) RunAndReturn(run func(ctx context.Context, token string) (*messages.ConfirmEmailResponseDTO, error)) *MockUserAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ForgotPassword provides a mock function for the type MockUserAuthServiceInterface
func (_mock *MockUserAuthServiceInterface) ForgotPassword(ctx context.Context, request *messages.ForgotPasswordRequestDTO) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.ForgotPasswordRequestDTO) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserAuthServiceInterface_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockUserAuthServiceInterface_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.ForgotPasswordRequestDTO
func (_e *MockUserAuthServiceInterface_Expecter) ForgotPassword(ctx interface{}, request interface{}) *MockUserAuthServiceInterface_ForgotPassword_Call {
	return &MockUserAuthServiceInterface_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, request)}
}

func (_c *MockUserAuthServiceInterface_ForgotPassword_Call) Run(run func(ctx context.Context, request *messages.ForgotPasswordRequestDTO)) *MockUserAuthServiceInterface_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.ForgotPasswordRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.ForgotPasswordRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAuthServiceInterface_ForgotPassword_Call) Return(err error) *MockUserAuthServiceInterface_ForgotPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserAuthServiceInterface_ForgotPassword_Call) RunAndReturn(run func(ctx context.Context, request *messages.ForgotPasswordRequestDTO) error) *MockUserAuthServiceInterface_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockUserAuthServiceInterface
func (_mock *MockUserAuthServiceInterface) Login(ctx context.Context, request *messages.LoginRequestDTO) (*messages.LoginResponseDTO, string, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *messages.LoginResponseDTO
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.LoginRequestDTO) (*messages.LoginResponseDTO, string, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.LoginRequestDTO) *messages.LoginResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.LoginResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.LoginRequestDTO) string); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *messages.LoginRequestDTO) error); ok {
		r2 = returnFunc(ctx, request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserAuthServiceInterface_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserAuthServiceInterface_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.LoginRequestDTO
func (_e *MockUserAuthServiceInterface_Expecter) Login(ctx interface{}, request interface{}) *MockUserAuthServiceInterface_Login_Call {
	return &MockUserAuthServiceInterface_Login_Call{Call: _e.mock.On("Login", ctx, request)}
}

func (_c *MockUserAuthServiceInterface_Login_Call) Run(run func(ctx context.Context, request *messages.LoginRequestDTO)) *MockUserAuthServiceInterface_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.LoginRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.LoginRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAuthServiceInterface_Login_Call) Return(loginResponseDTO *messages.LoginResponseDTO, s string, err error) *MockUserAuthServiceInterface_Login_Call {
	_c.Call.Return(loginResponseDTO, s, err)
	return _c
}

func (_c *MockUserAuthServiceInterface_Login_Call) RunAndReturn(run func(ctx context.Context, request *messages.LoginRequestDTO) (*messages.LoginResponseDTO, string, error)) *MockUserAuthServiceInterface_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserAuthServiceInterface
func (_mock *MockUserAuthServiceInterface) Register(ctx context.Context, request *messages.RegisterRequestDTO) (*messages.CreateUserResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *messages.CreateUserResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.RegisterRequestDTO) (*messages.CreateUserResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.RegisterRequestDTO) *messages.CreateUserResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.CreateUserResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.RegisterRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAuthServiceInterface_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserAuthServiceInterface_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.RegisterRequestDTO
func (_e *MockUserAuthServiceInterface_Expecter) Register(ctx interface{}, request interface{}) *MockUserAuthServiceInterface_Register_Call {
	return &MockUserAuthServiceInterface_Register_Call{Call: _e.mock.On("Register", ctx, request)}
}

func (_c *MockUserAuthServiceInterface_Register_Call) Run(run func(ctx context.Context, request *messages.RegisterRequestDTO)) *MockUserAuthServiceInterface_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.RegisterRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.RegisterRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAuthServiceInterface_Register_Call) Return(createUserResponseDTO *messages.CreateUserResponseDTO, err error) *MockUserAuthServiceInterface_Register_Call {
	_c.Call.Return(createUserResponseDTO, err)
	return _c
}

func (_c *MockUserAuthServiceInterface_Register_Call) RunAndReturn(run func(ctx context.Context, request *messages.RegisterRequestDTO) (*messages.CreateUserResponseDTO, error)) *MockUserAuthServiceInterface_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResendConfirmationEmail provides a mock function for the type MockUserAuthServiceInterface
func (_mock *MockUserAuthServiceInterface) ResendConfirmationEmail(ctx context.Context) (*messages.ResendConfirmationEmailResponseDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResendConfirmationEmail")
	}

	var r0 *messages.ResendConfirmationEmailResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*messages.ResendConfirmationEmailResponseDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *messages.ResendConfirmationEmailResponseDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.ResendConfirmationEmailResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAuthServiceInterface_ResendConfirmationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendConfirmationEmail'
type MockUserAuthServiceInterface_ResendConfirmationEmail_Call struct {
	*mock.Call
}

// ResendConfirmationEmail is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserAuthServiceInterface_Expecter) ResendConfirmationEmail(ctx interface{}) *MockUserAuthServiceInterface_ResendConfirmationEmail_Call {
	return &MockUserAuthServiceInterface_ResendConfirmationEmail_Call{Call: _e.mock.On("ResendConfirmationEmail", ctx)}
}

func (_c *MockUserAuthServiceInterface_ResendConfirmationEmail_Call) Run(run func(ctx context.Context)) *MockUserAuthServiceInterface_ResendConfirmationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserAuthServiceInterface_ResendConfirmationEmail_Call) Return(resendConfirmationEmailResponseDTO *messages.ResendConfirmationEmailResponseDTO, err error) *MockUserAuthServiceInterface_ResendConfirmationEmail_Call {
	_c.Call.Return(resendConfirmationEmailResponseDTO, err)
	return _c
}

func (_c *MockUserAuthServiceInterface_ResendConfirmationEmail_Call) RunAndReturn(run func(ctx context.Context) (*messages.ResendConfirmationEmailResponseDTO, error)) *MockUserAuthServiceInterface_ResendConfirmationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockUserAuthServiceInterface
func (_mock *MockUserAuthServiceInterface) UpdatePassword(ctx context.Context, request *messages.UpdatePasswordRequestDTO) (*messages.UpdatePasswordResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 *messages.UpdatePasswordResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.UpdatePasswordRequestDTO) (*messages.UpdatePasswordResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.UpdatePasswordRequestDTO) *messages.UpdatePasswordResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.UpdatePasswordResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.UpdatePasswordRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAuthServiceInterface_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockUserAuthServiceInterface_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.UpdatePasswordRequestDTO
func (_e *MockUserAuthServiceInterface_Expecter) UpdatePassword(ctx interface{}, request interface{}) *MockUserAuthServiceInterface_UpdatePassword_Call {
	return &MockUserAuthServiceInterface_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, request)}
}

func (_c *MockUserAuthServiceInterface_UpdatePassword_Call) Run(run func(ctx context.Context, request *messages.UpdatePasswordRequestDTO)) *MockUserAuthServiceInterface_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.UpdatePasswordRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.UpdatePasswordRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAuthServiceInterface_UpdatePassword_Call) Return(updatePasswordResponseDTO *messages.UpdatePasswordResponseDTO, err error) *MockUserAuthServiceInterface_UpdatePassword_Call {
	_c.Call.Return(updatePasswordResponseDTO, err)
	return _c
}

func (_c *MockUserAuthServiceInterface_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, request *messages.UpdatePasswordRequestDTO) (*messages.UpdatePasswordResponseDTO, error)) *MockUserAuthServiceInterface_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}
