// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/scienceandcode/nucleus-api/internal/domain/user/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepositoryInterface creates a new instance of MockUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepositoryInterface struct {
	mock.Mock
}

type MockUserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterface_Expecter {
	return &MockUserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) Create(ctx context.Context, user *entities.User) (*entities.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) (*entities.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) *entities.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockUserRepositoryInterface_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepositoryInterface_Create_Call {
	return &MockUserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepositoryInterface_Create_Call) Run(run func(ctx context.Context, user *entities.User)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) Return(user1 *entities.User, err error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) (*entities.User, error)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByID provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) ExistsByID(ctx context.Context, id uint64) bool {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockUserRepositoryInterface_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockUserRepositoryInterface_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockUserRepositoryInterface_Expecter) ExistsByID(ctx interface{}, id interface{}) *MockUserRepositoryInterface_ExistsByID_Call {
	return &MockUserRepositoryInterface_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, id)}
}

func (_c *MockUserRepositoryInterface_ExistsByID_Call) Run(run func(ctx context.Context, id uint64)) *MockUserRepositoryInterface_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_ExistsByID_Call) Return(b bool) *MockUserRepositoryInterface_ExistsByID_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockUserRepositoryInterface_ExistsByID_Call) RunAndReturn(run func(ctx context.Context, id uint64) bool) *MockUserRepositoryInterface_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) FindByEmail(ctx context.Context, email string) (*entities.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepositoryInterface_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepositoryInterface_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepositoryInterface_FindByEmail_Call {
	return &MockUserRepositoryInterface_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepositoryInterface_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepositoryInterface_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByEmail_Call) Return(user *entities.User, err error) *MockUserRepositoryInterface_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entities.User, error)) *MockUserRepositoryInterface_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) FindByID(ctx context.Context, id uint64) (*entities.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entities.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entities.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockUserRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepositoryInterface_FindByID_Call {
	return &MockUserRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByID_Call) Return(user *entities.User, err error) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*entities.User, error)) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) Update(ctx context.Context, user *entities.User) (*entities.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) (*entities.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) *entities.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockUserRepositoryInterface_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepositoryInterface_Update_Call {
	return &MockUserRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepositoryInterface_Update_Call) Run(run func(ctx context.Context, user *entities.User)) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) Return(user1 *entities.User, err error) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) (*entities.User, error)) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}
