// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	api2 "github.com/scienceandcode/nucleus-api/internal/infrastructure/di/api"
	"github.com/scienceandcode/nucleus-api/internal/infrastructure/di/db"
	"github.com/scienceandcode/nucleus-api/internal/infrastructure/di/db/repositories"
	"github.com/scienceandcode/nucleus-api/internal/infrastructure/di/services"
	"github.com/scienceandcode/nucleus-api/internal/presentation/api"
	"github.com/scienceandcode/nucleus-api/internal/presentation/api/handlers"
)

// Injectors from wire.go:

func InitializeServer() *api.API {
	engine := api2.ProvideEngine()
	healthcheckHandler := &handlers.HealthcheckHandler{}
	gormDB := db.ProvideDB()
	transactionManagerInterface := db.ProvideTransactionManager(gormDB)
	baseService := services.ProvideBaseService(transactionManagerInterface)
	userRepositoryInterface := repositories.ProvideUserRepository(gormDB)
	jwtServiceInterface := services.ProvideJwtService(baseService)
	emailServiceInterface := services.ProvideEmailService()
	emailConfirmationServiceInterface := services.ProvideEmailConfirmationService(baseService)
	userAuthServiceInterface := services.ProvideUserAuthService(baseService, userRepositoryInterface, jwtServiceInterface, emailServiceInterface, emailConfirmationServiceInterface)
	userAuthHandler := &handlers.UserAuthHandler{
		UserAuthService: userAuthServiceInterface,
	}
	taskRepositoryInterface := repositories.ProvideTaskRepository(gormDB)
	taskServiceInterface := services.ProvideTaskService(baseService, taskRepositoryInterface)
	taskHandler := &handlers.TaskHandler{
		TaskService: taskServiceInterface,
	}
	handlersHandlers := &handlers.Handlers{
		HealthcheckHandler: healthcheckHandler,
		UserAuthHandler:    userAuthHandler,
		TaskHandler:        taskHandler,
	}
	router := api2.ProvideRouter(engine, handlersHandlers)
	apiAPI := &api.API{
		Router: router,
	}
	return apiAPI
}
